version: '3.8'

services:
  kbc-quiz-backend:
    build:
      context: kbc-quiz
      dockerfile: Dockerfile
    container_name: kbc-quiz-backend
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: KbC420
      DB_PASSWORD: kBc#1357
      DB_DATABASE: kbc_quiz
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kbc-quiz-network

  db:
    image: postgres:13-alpine
    container_name: kbc-quiz-db
    environment:
      POSTGRES_DB: kbc_quiz
      POSTGRES_USER: KbC420
      POSTGRES_PASSWORD: kBc#1357
    ports:
      - '5433:5432'
    networks:
      - kbc-quiz-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U KbC420 -d kbc_quiz']
      interval: 10s
      timeout: 5s
      retries: 5

  kbc-quiz-frontend:
    build:
      context: ./quiz-app # Adjust the context to the Angular project directory
      dockerfile: Dockerfile
    container_name: kbc-quiz-frontend
    ports:
      - '4200:4200'
    networks:
      - kbc-quiz-network

networks:
  kbc-quiz-network:
    driver: bridge
